---
- name: "Neovim - Run Tasks: {{ ansible_distribution }}"   
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Neovim - Change privileges on config directory"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Neovim - Setup the config directory" 
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
